// ══ DATA ═════════════════════════════════════════════════════

const MEALS_1500 = {
  breakfast: [
    { name:"Anabolic French Toast + Greek Yogurt + Fruit", kcal:500, emoji:"🍞", desc:"1 serving Anabolic French Toast (270) + ¾ cup 0% plain Greek yogurt (100) + 1 serving fruit of choice (100) + low-calorie syrup (30)" },
    { name:"French Toast Blueberry Pancake + Yogurt + Syrup", kcal:460, emoji:"🥞", desc:"1 serving French Toast Blueberry Pancake (330) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + low-calorie syrup (30)" },
    { name:"Banana 'No'tella French Toast Roll-Ups + Yogurt", kcal:430, emoji:"🍌", desc:"1 serving Banana Notella French Toast Roll-Ups (340) + ¾ cup fat-free Greek yogurt (100)" },
    { name:"Egg White Avocado Rice Cake + Fruit", kcal:440, emoji:"🥑", desc:"1 serving Egg White Avocado Rice Cake (390) + ½ serving fruit of choice (50)" },
    { name:"Ham & Cheese Omelette + Yogurt + Fruit", kcal:445, emoji:"🍳", desc:"1 serving Ham & Cheese Omelette (295) + ⅓ cup fat-free Greek yogurt (50) + 1 serving fruit of choice (100)" },
    { name:"Oatmeal + Protein + Greek Yogurt", kcal:445, emoji:"🥣", desc:"½ cup (45g) Cream of Wheat or Oatmeal (165) + 1½ servings HTLT Whey+Casein Protein (180) + ¾ cup fat-free Greek yogurt (100)" },
    { name:"Toast + Egg Whites + Protein of Choice", kcal:430, emoji:"🍞", desc:"2 slices bread/toast (160) + 1.5 cups egg whites (180) + 90 cal of guacamole/avocado/turkey bacon/protein (90)" },
    { name:"Smoked Salmon Rice Cake Sandwich + Fruit", kcal:460, emoji:"🍣", desc:"3 servings Smoked Salmon Rice Cake Sandwich (360) + 1 serving fruit of choice (100)" },
  ],
  lunch: [
    { name:"Beef Burger (Extra Lean)", kcal:410, emoji:"🍔", desc:"120g extra lean ground beef (210) + 1 bread/bun (150) + lettuce/pickles/veggies (20) + sugar-free condiments (30)" },
    { name:"Anabolic Pizza Pockets + Fruit", kcal:410, emoji:"🍕", desc:"2 servings Anabolic Pizza Pockets (360) + ½ serving fruit or veggies of choice (50)" },
    { name:"Sloppy Greg Open-Faced + Fruit + Yogurt", kcal:425, emoji:"🥩", desc:"½ serving Sloppy Greg Open Faced (275) + 1 serving fruit or veggies (100) + ⅓ cup fat-free Greek yogurt (50)" },
    { name:"FlatOut Pizza with Bison + Fruit", kcal:410, emoji:"🍕", desc:"1 serving FlatOut Pizza with Bison (310) + 1 serving fruit or veggies of choice (100)" },
    { name:"Chicken/Turkey on Joseph's Lavash Wrap + Fruit", kcal:440, emoji:"🌯", desc:"1 serving Chicken or Turkey on Joseph's Lavash Wrap (290) + 1½ servings fruit or veggies (150)" },
    { name:"Spicy Shredded Chicken on Rice Cakes + Fruit", kcal:425, emoji:"🍗", desc:"1 serving Spicy Shredded Chicken on Rice Cakes (375) + ½ serving fruit or veggies (50)" },
    { name:"Smoked Salmon Pinwheels + Fruit", kcal:450, emoji:"🍣", desc:"2 servings Smoked Salmon Pinwheels (400) + ½ serving fruit or veggies of choice (50)" },
  ],
  dinner: [
    { name:"Chicken Cacciatore + Cauliflower Mash", kcal:405, emoji:"🍲", desc:"1 serving Chicken Cacciatore (255) + 1 serving Cauliflower Mashed Potatoes or ¾ cup rice (150)" },
    { name:"Lean Protein + Rice/Potato + Veggies", kcal:450, emoji:"🥩", desc:"90g salmon / 120g smoked salmon / 100g extra lean steak / 120g extra lean turkey / 140g chicken + ½ cup rice or 110g potato or 125g sweet potato + 1.5 servings veggies + condiments" },
    { name:"Anabolic Meat Lasagna + Fruit/Veggies", kcal:445, emoji:"🍝", desc:"1 serving Anabolic Meat Lasagna (345) + 1 serving fruit or veggies of choice (100)" },
    { name:"Citrus Tilapia, Shrimp & Veggies + Fruit", kcal:430, emoji:"🐟", desc:"1 serving Citrus Tilapia, Shrimp & Veggies (380) + ½ serving fruit or veggies of choice (50)" },
    { name:"Pedon MORE THAN Pasta + Fruit", kcal:440, emoji:"🍝", desc:"1 serving Pedon MORE THAN Pasta with Chicken & Tomato Sauce / small (290) + 1½ serving fruit of choice (150)" },
    { name:"Spicy Pork Chili Stew + Cauliflower Mash + Fruit", kcal:450, emoji:"🍲", desc:"1 serving Spicy Pork Chili Stew (250) + 1 serving Cauliflower Mashed Potatoes (150) + ½ serving fruit or veggies (50)" },
    { name:"Large Salad with Lean Protein", kcal:440, emoji:"🥗", desc:"200g chicken/turkey / 150g extra lean steak / 260g haddock or shrimp / 130g salmon + up to 450g spinach + Walden Farms toppings + 2 tbsp light dressing" },
  ],
  snacks: [
    { name:"Blueberry Protein Muffin", kcal:160, emoji:"🫐" },
    { name:"SKOR Protein Bar (Medium)", kcal:164, emoji:"🍫" },
    { name:"Smart Pop Popcorn", kcal:200, emoji:"🍿" },
    { name:"Jelly Filled Pronut", kcal:160, emoji:"🍩" },
    { name:"Chocolate Strawberry Proteinsicles", kcal:200, emoji:"🍓" },
    { name:"Chocolate PB Protein Ice Cream (small)", kcal:190, emoji:"🍦" },
    { name:"Chocolate Protein Mug Cake", kcal:200, emoji:"🍰" },
  ]
};

const MEALS_2000 = {
  breakfast: [
    { name:"2× Anabolic French Toast + Syrup", kcal:585, emoji:"🍞", desc:"2 servings Anabolic French Toast (540) + up to 45 cal low-calorie syrup (45)" },
    { name:"French Toast Blueberry Pancake + Yogurt + Fruit + Syrup", kcal:560, emoji:"🥞", desc:"1 serving French Toast Blueberry Pancake (330) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit of choice (100) + low-calorie syrup (30)" },
    { name:"Banana 'No'tella Roll-Ups + Yogurt + Fruit + Syrup", kcal:570, emoji:"🍌", desc:"1 serving Banana Notella French Toast Roll-Ups (340) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit (100) + low-calorie syrup (30)" },
    { name:"Egg White Avocado Rice Cake + Yogurt + Fruit", kcal:590, emoji:"🥑", desc:"1 serving Egg White Avocado Rice Cake (390) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit of choice (100)" },
    { name:"2× Ham & Cheese Omelette", kcal:590, emoji:"🍳", desc:"2 servings Ham & Cheese Omelette (590). No additions needed — this is a full 590-cal breakfast on its own!" },
    { name:"Oatmeal + Protein + Yogurt + Syrup", kcal:590, emoji:"🥣", desc:"1 cup (90g) Cream of Wheat or Oatmeal (330) + 1½ servings HTLT Whey+Casein Protein (180) + ⅓ cup fat-free Greek yogurt (50) + low-calorie syrup (30)" },
    { name:"Toast + Egg Whites + Protein of Choice", kcal:585, emoji:"🍳", desc:"2 slices bread/toast (160) + 3 cups egg whites (360) + 65 cal of guacamole/avocado/turkey bacon/protein (65)" },
  ],
  lunch: [
    { name:"Beef Burger + Fruit", kcal:580, emoji:"🍔", desc:"140g extra lean ground beef (280) + 1 bread/bun (150) + lettuce/pickles/veggies (20) + sugar-free condiments (30) + 1 serving fruit or veggies (100)" },
    { name:"3× Anabolic Pizza Pockets", kcal:585, emoji:"🍕", desc:"3 servings Anabolic Pizza Pockets (585). Simple, filling, and hits the target!" },
    { name:"Sloppy Greg + Fruit", kcal:600, emoji:"🥩", desc:"1 serving Sloppy Greg Open Faced (550) + ½ serving fruit or veggies of choice (50)" },
    { name:"FlatOut Pizza + Yogurt + Fruit", kcal:560, emoji:"🍕", desc:"1 serving FlatOut Pizza with Bison (310) + ¾ cup fat-free Greek yogurt (100) + ½ serving fruit or veggies (50)" },
    { name:"2× Joseph's Lavash Wrap", kcal:580, emoji:"🌯", desc:"2 servings Chicken or Turkey on Joseph's Lavash Wrap (580)" },
    { name:"Spicy Shredded Chicken + Yogurt + Fruit", kcal:575, emoji:"🍗", desc:"1 serving Spicy Shredded Chicken on Rice Cakes (375) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit or veggies (100)" },
    { name:"3× Smoked Salmon Pinwheels", kcal:600, emoji:"🍣", desc:"3 servings Smoked Salmon Pinwheels (600)" },
  ],
  dinner: [
    { name:"2× Chicken Cacciatore + Veggies", kcal:585, emoji:"🍲", desc:"2 servings Chicken Cacciatore (510) + ¾ serving fruit or veggies of choice (75)" },
    { name:"Larger Lean Protein + Rice/Potato + Veggies", kcal:580, emoji:"🥩", desc:"115g salmon / 145g smoked salmon / 130g extra lean steak / 155g extra lean ground turkey / 180g chicken / 230g haddock or shrimp / 200g tilapia + 1 cup rice or 225g potato + 1 serving veggies + condiments" },
    { name:"Anabolic Meat Lasagna + Yogurt + Fruit", kcal:595, emoji:"🍝", desc:"1 serving Anabolic Meat Lasagna (345) + ¾ cup fat-free Greek yogurt (100) + 1½ servings fruit or veggies (150)" },
    { name:"Citrus Tilapia + Yogurt + Fruit", kcal:580, emoji:"🐟", desc:"1 serving Citrus Tilapia, Shrimp & Veggies (380) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit or veggies (100)" },
    { name:"Pedon Pasta (Large) + Fruit", kcal:595, emoji:"🍝", desc:"1 serving Pedon MORE THAN Pasta with Chicken & Tomato Sauce — Large (545) + ½ serving fruit of choice (50)" },
    { name:"2× Spicy Pork Chili Stew + Fruit", kcal:600, emoji:"🍲", desc:"2 servings Spicy Pork Chili Stew (500) + 1 serving fruit or veggies of choice (100)" },
    { name:"Whitefish Coleslaw Tacos + Yogurt + Fruit", kcal:570, emoji:"🌮", desc:"1 serving Whitefish with Coleslaw Tacos (420) + ¾ cup fat-free Greek yogurt (100) + ½ serving fruit or veggies (50)" },
  ],
  snacks: [
    { name:"Blueberry Protein Muffin", kcal:160, emoji:"🫐" },
    { name:"SKOR Protein Bar (Medium)", kcal:164, emoji:"🍫" },
    { name:"Smart Pop Popcorn", kcal:200, emoji:"🍿" },
    { name:"Jelly Filled Pronut", kcal:160, emoji:"🍩" },
    { name:"Chocolate Strawberry Proteinsicles", kcal:200, emoji:"🍓" },
    { name:"Chocolate PB Protein Ice Cream (small)", kcal:190, emoji:"🍦" },
    { name:"Chocolate Protein Mug Cake", kcal:200, emoji:"🍰" },
  ]
};

const MEALS_2500 = {
  breakfast: [
    { name:"2× Anabolic French Toast + Fruit + Greek Yogurt + Syrup", kcal:785, emoji:"🍞",
      desc:"2 servings Anabolic French Toast (540) + 1 serving fruit of choice (100) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + up to 45 cal low-calorie syrup (45)" },
    { name:"2× French Toast Blueberry Pancake + Fruit + Syrup", kcal:740, emoji:"🥞",
      desc:"2 servings French Toast Blueberry Pancake (660) + ½ serving fruit of choice (50) + low-calorie syrup (30)" },
    { name:"2× Banana 'No'tella French Toast Roll-Ups + Fruit + Syrup", kcal:760, emoji:"🍌",
      desc:"2 servings Banana Notella French Toast Roll-Ups (680) + ½ serving fruit of choice (50) + low-calorie syrup (30)" },
    { name:"2× Egg White Avocado Rice Cake", kcal:780, emoji:"🥑",
      desc:"2 servings Egg White Avocado Rice Cake (780). A complete, filling breakfast on its own — no additions needed!" },
    { name:"2× Ham & Cheese Omelette + Fruit", kcal:740, emoji:"🍳",
      desc:"2 servings Ham & Cheese Omelette (590) + 1½ servings fruit of choice (150)" },
    { name:"XL Oatmeal + Protein + Greek Yogurt + Fruit + Syrup", kcal:740, emoji:"🥣",
      desc:"1 cup (90g) Cream of Wheat or Oatmeal (330) + 1½ servings HTLT Whey+Casein Protein (180) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + 1 serving fruit of choice (100) + low-calorie syrup (30)" },
    { name:"Toast + 3 Cups Egg Whites + Protein + Yogurt + Fruit", kcal:785, emoji:"🍳",
      desc:"2 slices bread/toast (160) + 3 cups egg whites (360) + 65 cal of guacamole/avocado/turkey bacon/protein of choice (65) + ¾ cup fat-free Greek yogurt (100) + 1 serving fruit of choice (100)" },
  ],
  lunch: [
    { name:"Beef Burger + Fruit + Smart Pop Popcorn", kcal:780, emoji:"🍔",
      desc:"140g extra lean ground beef (280) + 1 bread/bun (150) + lettuce/pickles/veggies (20) + sugar-free condiments (30) + 1 serving fruit or veggies of choice (100) + 1 bag Smart Pop Popcorn (200)" },
    { name:"4× Anabolic Pizza Pockets", kcal:780, emoji:"🍕",
      desc:"4 servings Anabolic Pizza Pockets (780). Simple, filling, and hits the target perfectly on its own!" },
    { name:"Sloppy Greg Open-Faced + Greek Yogurt + Fruit", kcal:750, emoji:"🥩",
      desc:"1 serving Sloppy Greg Open-Faced (550) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + 1 serving fruit of choice (100)" },
    { name:"2× FlatOut Pizza with Bison + Yogurt + Fruit", kcal:770, emoji:"🍕",
      desc:"2 servings FlatOut Pizza with Bison (620) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + ½ serving fruit or veggies of choice (50)" },
    { name:"Joseph's Lavash Wrap + Greek Yogurt + Fruit", kcal:610, emoji:"🌯",
      desc:"1 serving Chicken or Turkey on Joseph's Lavash Wrap (410) + ¾ cup fat-free no-sugar-added Greek yogurt (100) + 1 serving fruit or veggies of choice (100) · Lower end of the range — pair with an optional snack if still hungry" },
    { name:"2× Spicy Shredded Chicken on Rice Cakes", kcal:750, emoji:"🍗",
      desc:"2 servings Spicy Shredded Chicken on Rice Cakes (750). High-volume, high-protein — very filling!" },
    { name:"4× Smoked Salmon Pinwheels", kcal:800, emoji:"🍣",
      desc:"4 servings Smoked Salmon Pinwheels (800). Easy to prep ahead and take anywhere!" },
  ],
  dinner: [
    { name:"3× Chicken Cacciatore", kcal:765, emoji:"🍲",
      desc:"3 servings Chicken Cacciatore (765). Make a big batch on Sunday and portion out for the week!" },
    { name:"Large Lean Protein + 2 Cups Rice/Potato + Veggies", kcal:760, emoji:"🥩",
      desc:"180g chicken/turkey OR 240g haddock/cod/shrimp OR 220g YVES Veggie Ground Round OR 120g salmon OR 135g extra lean steak/bison OR 155g extra lean ground turkey (240) + 2 cups rice OR 1¾ cups Cauliflower Mashed Potato OR 450g any potato (400) + 1 serving veggies (100) + condiments (20)" },
    { name:"2× Anabolic Meat Lasagna + Fruit/Veggies", kcal:790, emoji:"🍝",
      desc:"2 servings Anabolic Meat Lasagna (690) + 1 serving fruit or veggies of choice (100)" },
    { name:"2× Citrus Tilapia, Shrimp & Veggies", kcal:760, emoji:"🐟",
      desc:"2 servings Citrus Tilapia, Shrimp & Veggies (760). Huge, flavorful, and almost zero calorie density from all the vegetables!" },
    { name:"Pedon MORE THAN Pasta (Large) + Fruit + Greek Yogurt", kcal:745, emoji:"🍝",
      desc:"1 serving Pedon MORE THAN Pasta with Chicken & Tomato Sauce — Large (545) + 1 serving fruit of choice (100) + ¾ cup fat-free no-sugar-added Greek yogurt (100)" },
    { name:"3× Spicy Pork Chili Stew", kcal:750, emoji:"🍲",
      desc:"3 servings Spicy Pork Chili Stew (750). Prep the full batch — each serving is only 250 cal and packed with lean protein!" },
    { name:"Whitefish with Coleslaw Tacos + Smart Pop + Fruit", kcal:770, emoji:"🌮",
      desc:"1 serving Whitefish with Coleslaw Tacos (420) + 1 bag Smart Pop Popcorn (200) + 1½ servings fruit or veggies of choice (150)" },
  ],
  snacks: [
    { name:"Blueberry Protein Muffin or Carrot Apple Muffin", kcal:160, emoji:"🫐" },
    { name:"SKOR Protein Bar (Medium) or CICO Bar", kcal:164, emoji:"🍫" },
    { name:"Smart Pop Popcorn (1 bag)", kcal:200, emoji:"🍿" },
    { name:"Jelly Filled Pronut", kcal:160, emoji:"🍩" },
    { name:"Chocolate Strawberry Almond Proteinsicles", kcal:200, emoji:"🍓" },
    { name:"Chocolate PB Protein Ice Cream (small)", kcal:190, emoji:"🍦" },
    { name:"Chocolate Protein Mug Cake", kcal:200, emoji:"🍰" },
  ]
};

const MEALS_BD1500 = {
  breakfast: [
    { name:"Dim er Bhurji + Brown Bread + Doi (Egg Scramble)", kcal:400, emoji:"🍳",
      desc:"7 egg whites scrambled with onion, tomato, green chili & turmeric (~120 cal) + 2 slices Westin/Olympic brown bread (160 cal) + ½ cup Arong/Danish plain doi (80 cal) + 1 tsp mustard oil in cooking only · Brand tip: Olympic or Westin brown bread from Agora/Meena Bazaar" },
    { name:"Quaker Oats + Milk + Banana + Doi", kcal:420, emoji:"🥣",
      desc:"½ cup Quaker/Saffola oats cooked with 100ml Milk Vita/Danish toned milk (165 cal) + 5 egg whites scrambled (85 cal) + 1 medium banana (90 cal) + ½ cup Arong plain doi (80 cal) · Brand tip: Quaker oats & Saffola oats both available at Agora, Meena Bazaar, Shwapno" },
    { name:"Chira (Flattened Rice) + Doi + Seasonal Fruits", kcal:389, emoji:"🌾",
      desc:"70g dry chira (flattened/beaten rice) soaked in water then drained (245 cal) + 1 cup Arong/Farm Fresh plain doi (80 cal) + 1 medium guava/peyara (37 cal) + ½ cup papaya/pepe (27 cal) · Very filling, zero cooking needed — a classic Bangladeshi high-protein light breakfast" },
    { name:"Atta Roti + Egg & Vegetable Omelette", kcal:400, emoji:"🫓",
      desc:"2 whole wheat atta rotis (180 cal) + 6 egg whites + 1 whole egg omelette (170 cal) with onion, tomato, green chili, capsicum (50 cal) · Minimal oil, non-stick pan. Atta flour available everywhere; use ACI or PRAN brand for consistency" },
    { name:"Suji (Semolina) Porridge + Egg Whites + Fruit", kcal:375, emoji:"🫕",
      desc:"50g suji porridge cooked with 150ml Danish/Milk Vita toned milk, no sugar (200 cal) + 5 egg whites scrambled with chili & onion (85 cal) + 1 medium banana (90 cal) · Add a little salt and green chili to the suji for a savory twist instead of sweet" },
    { name:"Moong Dal Omelette Roll (Dal Pitha style)", kcal:405, emoji:"🥙",
      desc:"30g moong dal boiled & lightly spiced (105 cal) + 5 egg whites omelette with vegetables (85 cal + 40 cal) + 1 whole wheat roti (90 cal) + ½ cup Arong plain doi (80 cal) · Moong dal from local bazar; this is high-fiber, high-protein and very filling" },
    { name:"Brown Rice + Masoor Dal + Egg Whites Plate", kcal:328, emoji:"🍚",
      desc:"½ cup cooked brown rice — Miniket brown or Nazirshail (108 cal) + ½ cup cooked masoor dal/red lentils (115 cal) + 5 egg whites scrambled with vegetables (85 cal) + cucumber salad (20 cal) · Brown rice from Agora/Meena Bazaar; masoor dal from any local bazar" },
  ],
  lunch: [
    { name:"Rui/Katla Macher Jhol + Rice + Dal + Vegetables", kcal:435, emoji:"🐟",
      desc:"120g rui or katla fish piece in light onion-tomato-turmeric curry, minimal oil (120 cal) + ¾ cup cooked white rice (146 cal) + ½ cup masoor/moong dal (115 cal) + 1 serving vegetable bhaji — lau/jhinga/shim (50 cal) · The classic Bangladeshi plate; just use minimal oil and rinse the fish before cooking" },
    { name:"Chicken Breast Curry + Rice + Dal + Veg Bhaji", kcal:440, emoji:"🍗",
      desc:"100g skinless chicken breast in light onion-garlic-ginger curry, minimal oil (165 cal) + ¾ cup cooked rice (146 cal) + ½ cup moong dal (80 cal) + mixed vegetable bhaji — ful kopi/cabbage/beans (50 cal) · Ask your butcher for 'boner chara murgi' — boneless skinless chicken" },
    { name:"Tilapia/Pangash Tawa Fry + Dal + Rice", kcal:440, emoji:"🐠",
      desc:"130g tilapia or pangash fillet, lightly pan-fried with minimal oil, turmeric & chili (130 cal) + ¾ cup rice (146 cal) + ½ cup masoor dal (115 cal) + 1 serving salad/vegetable (50 cal) · Tilapia and pangash are very lean fish — affordable and widely available at any bazar" },
    { name:"Chingri (Shrimp) Curry + Rice + Dal", kcal:396, emoji:"🦐",
      desc:"120g small/medium shrimp in light tomato-onion curry, minimal oil (120 cal) + ¾ cup rice (146 cal) + ½ cup dal (100 cal) + salad (30 cal) · Golda or bagda chingri are higher calorie — use smaller chingri (chhoto chingri) for a leaner meal" },
    { name:"Grilled Chicken Breast Roti Wrap + Doi", kcal:465, emoji:"🌯",
      desc:"100g grilled/boiled chicken breast (165 cal) shredded + 2 whole wheat atta rotis (180 cal) + cucumber, tomato, onion, green chili salad (40 cal) + ½ cup Arong doi (80 cal) · Shred the boiled chicken, mix with chili sauce — makes a satisfying wrap" },
    { name:"Boiled Egg + Egg White Curry + Rice + Dal", kcal:435, emoji:"🥚",
      desc:"2 hard-boiled whole eggs in light curry (140 cal) + 3 egg whites added to same curry (51 cal) + ¾ cup rice (146 cal) + ½ cup dal (80 cal) + vegetable (20 cal) · One pot, cheap, high protein — a classic Bangladeshi budget-friendly option" },
    { name:"Canned Tuna Salad + Atta Roti", kcal:415, emoji:"🥗",
      desc:"1 can (185g) tuna in water, drained — Century Tuna or similar (170 cal) + mixed salad with tomato, cucumber, onion, lemon juice (50 cal) + 2 whole wheat atta rotis (180 cal) · Canned tuna available at Agora, Meena Bazaar, Unimart — no cooking required" },
  ],
  dinner: [
    { name:"Grilled Chicken Breast + Vegetable Bhaji + Roti", kcal:425, emoji:"🍗",
      desc:"120g grilled or boiled chicken breast (198 cal) + mixed vegetable bhaji — band kopi, shim, gazar, ful kopi with minimal oil (80 cal) + 1 whole wheat roti (90 cal) + cucumber-tomato salad (20 cal) · Dinner goal: lean protein + fiber-rich veg, minimal rice or bread" },
    { name:"Steamed/Boiled Tilapia + Dal Soup + Rice", kcal:405, emoji:"🐟",
      desc:"140g tilapia or pangash steamed/boiled with ginger, garlic, green chili (140 cal) + ½ cup thin masoor dal soup (115 cal) + ½ cup cooked rice (97 cal) + 1 serving salad (20 cal) · Steaming removes all added fat — maximum protein for minimum calories" },
    { name:"Chicken Clear Soup + Vegetables + Roti", kcal:417, emoji:"🍲",
      desc:"150g chicken breast in clear broth soup with lau, cauliflower, carrot, beans — minimal oil (247+80 = 327 cal) + 1 atta roti (90 cal) · High volume, very filling, almost zero fat. Add ginger and green chili for flavor without calories" },
    { name:"Egg White Curry + Brown Rice + Dal", kcal:410, emoji:"🥚",
      desc:"8 egg whites in light onion-tomato curry, minimal oil (136 cal) + ½ cup cooked brown rice (108 cal) + ½ cup masoor dal (115 cal) + cucumber salad (20 cal) · 8 egg whites = ~28g protein. This is a powerhouse low-calorie high-protein dinner" },
    { name:"Chingri (Shrimp) Vegetable Stir-fry + Rice + Dal", kcal:420, emoji:"🦐",
      desc:"120g shrimp stir-fried with mixed vegetables — ful kopi, capsicum, beans, onion — minimal oil (175 cal) + ½ cup rice (97 cal) + ½ cup dal (100 cal) + salad (20 cal) · High protein, colorful, quick to make. Use 1 tsp oil maximum" },
    { name:"Boiled Rui + Moong Dal Soup + Rice", kcal:400, emoji:"🍚",
      desc:"150g boiled rui fish with turmeric and salt (150 cal) + ½ cup thin moong dal soup (100 cal) + ½ cup cooked rice (97 cal) + green chili & lemon (10 cal) · The simplest possible clean meal. Boiling the fish removes all fat and keeps it very lean" },
    { name:"Boiled Chicken + Steamed Veg + Brown Rice", kcal:430, emoji:"🥦",
      desc:"150g boiled skinless chicken breast (247 cal) + steamed cauliflower, cabbage, carrot, green beans (80 cal) + ½ cup brown rice (108 cal) · Prep all three in one pot. Season with salt, ginger, green chili, lemon juice — zero added oil needed" },
  ],
  snacks: [
    { name:"Arong/Danish Plain Doi + Guava", kcal:117, emoji:"🍶" },
    { name:"2 Boiled Eggs + Cucumber", kcal:150, emoji:"🥚" },
    { name:"Roasted Chana (Bengal Gram) 50g", kcal:170, emoji:"🫘" },
    { name:"Egg White Omelette + 1 Roti", kcal:165, emoji:"🍳" },
    { name:"Mixed Fruit Chaat (papaya/guava/watermelon)", kcal:180, emoji:"🍉" },
    { name:"PRAN Flavored Yogurt Cup + Guava", kcal:160, emoji:"🥛", approx:true },
    { name:"Canned Tuna (90g) + 3 Olympic Crackers", kcal:165, emoji:"🐟", approx:true },
  ]
};

const MEALS_BD2000 = {
  breakfast: [
    { name:"Large Egg White Bhurji + 3 Brown Bread Slices + Doi", kcal:520, emoji:"🍳",
      desc:"10 egg whites scrambled with onion, tomato, green chili & turmeric (~170 cal) + 3 slices Westin/Olympic brown bread (240 cal) + 1 cup Arong/Danish plain doi (80 cal) + ½ cup papaya on the side (30 cal) · Brand tip: Olympic brown bread from Agora/Shwapno; keep egg whites in bulk — buy 2 dozen eggs at once" },
    { name:"Large Oats Bowl + Eggs + Doi + 2 Bananas", kcal:580, emoji:"🥣",
      desc:"¾ cup Quaker/Saffola oats cooked with 150ml Danish toned milk (220 cal) + 6 egg whites scrambled (102 cal) + 2 medium bananas (180 cal) + ½ cup Arong plain doi (80 cal) · Prep the oats with milk for creaminess; the dual banana gives natural sweetness — no sugar needed" },
    { name:"Chira + Doi + Full Fruit Plate", kcal:565, emoji:"🌾",
      desc:"90g dry chira (flattened rice) soaked and drained (315 cal) + 1 cup Arong/Farm Fresh plain doi (80 cal) + 1 medium banana (90 cal) + 1 medium guava (37 cal) + ½ cup papaya (27 cal) · Great for rest days when you want something light to digest but still filling enough to hit your target" },
    { name:"3 Atta Rotis + Large Egg & Veg Omelette + Doi", kcal:580, emoji:"🫓",
      desc:"3 whole wheat rotis (270 cal) + 8 egg whites + 1 whole egg omelette (190 cal) with mixed vegetables (50 cal) + ½ cup Arong doi (80 cal) · This is a hearty Bangladeshi-style breakfast that will keep you full through a long workout" },
    { name:"Large Suji Porridge + Egg Whites + 2 Bananas", kcal:575, emoji:"🫕",
      desc:"70g suji cooked with 200ml Danish/Milk Vita low-fat milk, no sugar (280 cal) + 7 egg whites scrambled (119 cal) + 1 medium banana (90 cal) + ½ cup Arong doi (80 cal) · Savory suji with egg whites is a surprisingly satisfying combo — add turmeric and green chili for flavor" },
    { name:"Dal Omelette Roll + 2 Rotis + Doi + Fruit", kcal:570, emoji:"🥙",
      desc:"40g moong dal boiled & spiced (140 cal) + 7 egg whites omelette with vegetables (120+50 cal) + 2 whole wheat rotis (180 cal) + ½ cup Arong doi (80 cal) · This meal is incredibly protein-dense — the moong dal + egg whites combination gives ~40g protein" },
    { name:"Larger Brown Rice + Dal + Egg Whites Plate", kcal:523, emoji:"🍚",
      desc:"¾ cup cooked brown rice (162 cal) + ¾ cup cooked masoor dal (172 cal) + 7 egg whites scrambled with vegetables (119+50 = 169 cal) + cucumber-tomato salad (20 cal) · Solid all-day energy. Brown rice available at Agora — look for Miniket brown or BRAC brown rice" },
  ],
  lunch: [
    { name:"Larger Rui/Katla Jhol + Rice + Dal + Vegetables", kcal:580, emoji:"🐟",
      desc:"170g rui or katla fish in light curry, minimal oil (170 cal) + 1 cup cooked rice (195 cal) + ½ cup dal (115 cal) + 1 serving vegetable bhaji (60 cal) · This is the ultimate clean Bangladeshi bulk meal — affordable, high protein, and satisfying. Rinse the fish curry and skim oil off the top" },
    { name:"150g Chicken Breast Curry + Rice + Dal + Veg", kcal:585, emoji:"🍗",
      desc:"150g skinless chicken breast curry (247 cal) + 1 cup cooked rice (195 cal) + ½ cup moong dal (80 cal) + mixed vegetable bhaji (60 cal) · Increase protein by adding 3 egg whites to the curry before serving — adds ~51 cal and ~10g protein" },
    { name:"Large Tilapia Tawa Fry + Dal + Rice + Veg", kcal:575, emoji:"🐠",
      desc:"180g tilapia fillet pan-fried with minimal oil (180 cal) + 1 cup rice (195 cal) + ½ cup masoor dal (115 cal) + 1 serving vegetables (60 cal) + salad (20 cal) · Tilapia is one of the highest protein-per-taka fish in Bangladesh — buy fresh from any wet market" },
    { name:"Larger Chingri Curry + Rice + Dal + Veg", kcal:575, emoji:"🦐",
      desc:"170g shrimp in light curry (170 cal) + 1 cup rice (195 cal) + ½ cup dal (115 cal) + mixed vegetable bhaji (60 cal) + salad (20 cal) · Use small chingri (chhoto chingri) — leaner and cheaper than golda chingri while providing even more protein per 100g" },
    { name:"Chicken Breast Roti Wrap × 3 + Doi", kcal:580, emoji:"🌯",
      desc:"130g grilled/boiled chicken breast shredded (215 cal) + 3 whole wheat atta rotis (270 cal) + cucumber, tomato, onion salad (50 cal) + ½ cup Arong doi (80 cal) · Pack this as lunch-to-go in a tiffin box — no reheating needed, stays fresh for hours" },
    { name:"Larger Egg Curry + Rice + Dal + Vegetables", kcal:580, emoji:"🥚",
      desc:"3 whole eggs + 4 egg whites in light curry (210+68 = 278 cal) + 1 cup rice (195 cal) + ½ cup dal (80 cal) + vegetable bhaji (50 cal) · Budget-friendly high-protein lunch — add ginger-garlic paste and tomato for a rich curry without heavy oil" },
    { name:"Full Can Tuna + Large Salad + 3 Atta Rotis + Doi", kcal:585, emoji:"🥗",
      desc:"1 full can (185g) tuna in water drained (170 cal) + large mixed salad — tomato, cucumber, onion, lettuce, lemon (60 cal) + 3 whole wheat rotis (270 cal) + ½ cup Arong doi (80 cal) · Century Tuna (brine) available at Agora and Meena Bazaar. Fastest high-protein lunch with zero cooking" },
  ],
  dinner: [
    { name:"Larger Chicken Breast + Vegetable Bhaji + 2 Rotis + Doi", kcal:580, emoji:"🍗",
      desc:"170g grilled/boiled chicken breast (280 cal) + large mixed vegetable bhaji — band kopi, shim, gazar, ful kopi (100 cal) + 2 whole wheat rotis (180 cal) + ½ cup Arong doi (80 cal) · This dinner has ~55g protein. Prep the chicken by boiling in salted water with ginger — simple and clean" },
    { name:"Steamed Fish + Dal Soup + Brown Rice + Veg", kcal:575, emoji:"🐟",
      desc:"190g tilapia/pangash steamed with ginger & chili (190 cal) + ¾ cup thin masoor dal soup (172 cal) + ½ cup brown rice (108 cal) + vegetable salad (40 cal) · Steaming is the gold standard cooking method for fish — zero added fat, maximum protein retained" },
    { name:"Larger Chicken Soup + Vegetables + 2 Rotis + Doi", kcal:575, emoji:"🍲",
      desc:"200g chicken breast in clear vegetable broth — lau, ful kopi, gazar, beans (330+80 = 410 cal) + 2 atta rotis (180 cal) + ½ cup Arong doi (80 cal) · Make a big batch on Sunday — this soup reheats perfectly all week. Season with ginger, turmeric, green chili, salt" },
    { name:"Larger Egg White Curry + Brown Rice + Dal + Salad", kcal:514, emoji:"🥚",
      desc:"12 egg whites in light onion-tomato curry (204 cal) + ½ cup brown rice (108 cal) + ¾ cup masoor dal (172 cal) + salad (30 cal) · 12 egg whites = ~42g protein at only 204 cal. This is Greg Doucette-level efficiency applied to Bangladeshi cooking" },
    { name:"Larger Chingri Stir-fry + Rice + Dal + Doi", kcal:575, emoji:"🦐",
      desc:"170g shrimp stir-fried with mixed colorful vegetables, 1 tsp oil (200 cal) + ¾ cup rice (146 cal) + ½ cup dal (115 cal) + ½ cup Arong doi (80 cal) · High volume, colorful, genuinely satisfying. Add plenty of garlic, ginger, and green chili for zero-calorie flavor" },
    { name:"Boiled Rui + Moong Dal Soup + Brown Rice + Doi", kcal:570, emoji:"🍚",
      desc:"200g boiled rui fish with turmeric, salt, green chili (200 cal) + ¾ cup moong dal soup (172 cal) + ½ cup brown rice (108 cal) + ½ cup Arong doi (80 cal) · The cleanest possible Bangladeshi dinner. No oil required — the fish steams in its own moisture with a splash of water" },
    { name:"Boiled Chicken + Steamed Veg + Brown Rice + Doi", kcal:575, emoji:"🥦",
      desc:"200g boiled chicken breast (330 cal) + steamed cauliflower, cabbage, carrots, shim (80 cal) + ½ cup brown rice (108 cal) + ½ cup Arong doi (80 cal) · Meal prep this on training days — cook a large batch of chicken and rice, portion into containers for the week" },
  ],
  snacks: [
    { name:"Arong Doi + 2 Fruits (banana + guava)", kcal:207, emoji:"🍶" },
    { name:"3 Boiled Eggs", kcal:210, emoji:"🥚" },
    { name:"Roasted Chana 60g + Cucumber", kcal:215, emoji:"🫘" },
    { name:"2× Egg White Omelette (5 whites each)", kcal:170, emoji:"🍳" },
    { name:"Large Mixed Fruit Chaat", kcal:200, emoji:"🍉" },
    { name:"2× PRAN Flavored Yogurt Cups", kcal:220, emoji:"🥛", approx:true },
    { name:"Full Can Tuna + 4 Olympic Crackers", kcal:230, emoji:"🐟", approx:true },
  ]
};

const MEALS_BD2500 = {
  breakfast: [
    { name:"Giant Egg White Bhurji + 3 Brown Bread + Doi + 2 Bananas", kcal:766, emoji:"🍳",
      desc:"12 egg whites scrambled with onion, tomato, green chili & turmeric (204+60=264 cal) + 3 slices Olympic/Westin brown bread (240 cal) + 1 cup Arong/Danish plain doi (120 cal) + 2 medium bananas (180 cal) · This meal delivers ~45g protein. Prep the bhurji on a non-stick pan with cooking spray. Brown bread available at Agora & Shwapno — look for Olympic Whole Wheat" },
    { name:"XXL Oats Bowl + Egg Whites + 2 Bananas + Large Doi", kcal:762, emoji:"🥣",
      desc:"1 cup (90g) Quaker/Saffola oats cooked with 200ml Danish toned milk (330+70=400 cal) + 8 egg whites scrambled (136 cal) + 2 medium bananas (180 cal) + ½ cup Arong plain doi (80 cal) · The biggest, most filling breakfast on the plan. Cook oats thick with milk — no sugar needed when you have ripe bananas. Meal-prep the oats in 5 min the night before" },
    { name:"Large Chira Bowl + Egg Whites + Doi + 2 Bananas + Guava", kcal:757, emoji:"🌾",
      desc:"100g dry chira (flattened rice) soaked & drained (350 cal) + 8 egg whites scrambled (136 cal) + ½ cup Arong/Farm Fresh plain doi (80 cal) + 1 banana (90 cal) + 1 guava (37 cal) + ½ cup papaya (27 cal) · Great no-cook chira base — soaking for 10 min makes it soft and fluffy. Zero cooking needed for the chira; scramble the whites separately" },
    { name:"Dal-Egg Omelette Roll + 4 Atta Rotis + Doi + Banana", kcal:773, emoji:"🥙",
      desc:"40g moong dal boiled & spiced (140 cal) + 8 egg whites omelette with mixed veg (136+60=196 cal) + 4 whole wheat atta rotis (360 cal) + ½ cup Arong doi (80 cal) · Moong dal + egg whites = ~40g protein in the omelette alone. Make the dal paste the night before; assemble in 5 min. Atta from ACI or PRAN brand — consistent rotis every time" },
    { name:"Large Suji + 10 Egg Whites + 2 Bananas + Doi", kcal:760, emoji:"🫕",
      desc:"100g suji cooked with 200ml Danish/Milk Vita low-fat milk, no sugar (350+70=420 cal) + 10 egg whites scrambled with green chili & turmeric (170 cal) + 1 banana (90 cal) + ½ cup Arong doi (80 cal) · Savory suji is surprisingly satisfying at high calories. Add turmeric, green chili, and a pinch of salt for a desi-style porridge that beats sweet versions" },
    { name:"3 Atta Rotis + XXL Egg & Veg Omelette + Doi + 2 Fruits", kcal:779, emoji:"🫓",
      desc:"3 whole wheat rotis (270 cal) + 12 egg whites + 1 whole egg omelette (204+17+60=281 cal) + 1 cup Arong doi (120 cal) + guava + ½ cup papaya (37+27=64 cal) · Classic Bangladeshi desi breakfast scaled up. The whole egg adds richness without major calories. Use a large non-stick pan to cook the giant omelette in one go" },
    { name:"Brown Rice + Dal + XXL Egg White Bhurji + Doi + Fruit", kcal:786, emoji:"🍚",
      desc:"1 cup cooked brown rice (216 cal) + ¾ cup masoor dal (172 cal) + 10 egg whites bhurji with veg (170+60=230 cal) + ½ cup Arong doi (80 cal) + 1 banana (90 cal) · Solid all-day energy. Brown rice from Agora (Miniket brown or BRAC brown). Breakfast rice is common in BD — this version is lean, high-protein, and genuinely filling at 2500 cal" },
  ],
  lunch: [
    { name:"Large Rui/Katla Jhol + 1.5 cup Rice + Dal + Veg + Salad", kcal:765, emoji:"🐟",
      desc:"200g rui or katla fish in light onion-tomato-turmeric curry, minimal oil (200 cal) + 1.5 cups cooked rice (293 cal) + ¾ cup masoor dal (172 cal) + mixed vegetable bhaji (80 cal) + cucumber-tomato salad (20 cal) · The king of Bangladeshi clean bulk meals — high protein, affordable, satisfying. Skim oil off the jhol surface before serving. Rinse the fish before cooking" },
    { name:"180g Chicken Breast Curry + Rice + Dal + Veg Bhaji + Doi", kcal:767, emoji:"🍗",
      desc:"180g skinless chicken breast curry, minimal oil (297 cal) + 1 cup cooked rice (195 cal) + ½ cup moong dal (115 cal) + mixed veg bhaji — ful kopi, shim, gazar (80 cal) + ½ cup Arong doi (80 cal) · Ask your butcher for 'boner chara murgi'  (boneless skinless). Add 3 egg whites to the curry just before serving — boosts protein by ~10g for only 51 extra cal" },
    { name:"220g Tilapia Jhol + 1.5 cup Rice + Dal + Veg", kcal:760, emoji:"🐠",
      desc:"220g tilapia fillet in light jhol, minimal oil (220 cal) + 1.5 cups cooked rice (293 cal) + ¾ cup masoor dal (172 cal) + mixed vegetable bhaji (80 cal) · Tilapia is one of the highest protein-per-taka fish in Bangladesh — lean, widely available, fast to cook. Buy fresh from any wet market. Minimal oil = maximum calorie efficiency" },
    { name:"200g Chingri Curry + 1.5 cup Rice + Dal + Veg + Doi", kcal:770, emoji:"🦐",
      desc:"200g small/medium shrimp in light curry, minimal oil (200 cal) + 1.5 cups cooked rice (293 cal) + ½ cup dal (115 cal) + vegetable bhaji (80 cal) + ½ cup Arong doi (80 cal) · Use chhoto chingri (small shrimp) — leaner than golda or bagda, and cheaper. High protein, colorful, and quick to cook. Add plenty of garlic, ginger, and green chili for zero-calorie flavor" },
    { name:"Chicken Roti Wrap ×4 + Doi + Banana", kcal:774, emoji:"🌯",
      desc:"150g boiled/grilled chicken breast shredded (247 cal) + 4 whole wheat atta rotis (360 cal) + cucumber, tomato, onion, green chili salad (50 cal) + ½ cup Arong doi (80 cal) + ½ banana (45 cal) · The ultimate lunchbox meal — pack in a tiffin box, stays fresh for hours, zero reheating. Season the chicken with mustard, lemon juice, and chili for flavor without calories" },
    { name:"Large Egg Curry + 1.5 cup Rice + Dal + Veg Bhaji", kcal:762, emoji:"🥚",
      desc:"2 whole eggs + 6 egg whites in light onion-tomato curry (140+102+60=302 cal) + 1.5 cups cooked rice (293 cal) + ½ cup dal (115 cal) + vegetable bhaji (80 cal) · Budget-friendly high-protein lunch. The 6 extra egg whites in the curry add protein without the fat of yolks. One pot, cheap, and makes excellent leftovers for the next day" },
    { name:"Full Can Tuna + 4 Atta Rotis + Large Salad + Doi + Banana", kcal:760, emoji:"🥗",
      desc:"185g can tuna in brine, drained — Century Tuna or similar (170 cal) + 4 whole wheat atta rotis (360 cal) + large mixed salad — tomato, cucumber, onion, lettuce, lemon (60 cal) + ½ cup Arong doi (80 cal) + ½ banana (45 cal) · Fastest high-protein lunch on the plan — zero cooking required. Canned tuna is ~37g protein per 185g can" },
  ],
  dinner: [
    { name:"170g Chicken Breast + Large Veg Bhaji + 3 Rotis + Doi + Fruit", kcal:767, emoji:"🍗",
      desc:"170g boiled/grilled skinless chicken breast (280 cal) + large mixed vegetable bhaji — band kopi, shim, gazar, ful kopi with minimal oil (100 cal) + 3 atta rotis (270 cal) + ½ cup Arong doi (80 cal) + 1 guava (37 cal) · ~55g protein dinner. Boil the chicken in salted water with ginger for maximum flavor without fat. Prep on Sunday for the whole week" },
    { name:"250g Steamed Tilapia + Dal Soup + Brown Rice + Doi + Veg", kcal:762, emoji:"🐟",
      desc:"250g tilapia/pangash steamed with ginger, garlic & green chili (250 cal) + 1 cup thin masoor dal soup (230 cal) + ½ cup cooked brown rice (108 cal) + ½ cup Arong doi (80 cal) + salad (40 cal) · Steaming is the gold standard — zero added fat, maximum protein retained. Make the dal soup very thin (almost broth-like) so it's high-volume and filling" },
    { name:"180g Chicken Soup + Vegetables + ½ cup Brown Rice + 2 Rotis + Doi", kcal:765, emoji:"🍲",
      desc:"180g chicken breast in clear veg broth — lau, ful kopi, gazar, beans (297+100=397 cal) + ½ cup brown rice (108 cal) + 2 atta rotis (180 cal) + ½ cup Arong doi (80 cal) · Batch-cook this soup on Sunday — reheats perfectly all week. Season with ginger, turmeric, green chili, salt. The broth tricks your brain into feeling fuller than the calories suggest" },
    { name:"15 Egg Whites Curry + 1 cup Brown Rice + Dal + Doi + Salad", kcal:757, emoji:"🥚",
      desc:"15 egg whites in light onion-tomato-ginger curry, minimal oil (255+60=315 cal) + 1 cup cooked brown rice (216 cal) + ½ cup masoor dal (115 cal) + ½ cup Arong doi (80 cal) + salad (30 cal) · 15 egg whites = ~52g protein at only 255 cal. This is Greg Doucette MAINGAIN philosophy applied to Bangladeshi cooking. The high volume of whites makes this dinner enormously filling" },
    { name:"200g Chingri Stir-fry + Veg + 1 cup Rice + Dal + Doi + Salad", kcal:765, emoji:"🦐",
      desc:"200g shrimp stir-fried with colorful mixed vegetables — capsicum, beans, ful kopi, onion, 1 tsp oil (200+80+45=325 cal) + 1 cup cooked rice (195 cal) + ½ cup dal (115 cal) + ½ cup Arong doi (80 cal) + salad (30 cal) · High volume, colorful, genuinely satisfying. Use chhoto chingri for a leaner stir-fry. This dish looks and tastes more decadent than the calorie count suggests" },
    { name:"260g Boiled Rui + Brown Rice + Dal + Doi + Veg + Salad", kcal:755, emoji:"🍚",
      desc:"260g boiled rui fish with turmeric, salt & green chili (260 cal) + 1 cup cooked brown rice (216 cal) + ½ cup moong dal (115 cal) + ½ cup Arong doi (80 cal) + mixed veg (60 cal) + salad (20 cal) · The cleanest possible Bangladeshi dinner, scaled up for 2500 cal. No oil required — the rui steams in its own moisture with a splash of water, turmeric & green chili" },
    { name:"200g Boiled Chicken + Steamed Veg + Brown Rice + Doi + Banana", kcal:762, emoji:"🥦",
      desc:"200g boiled skinless chicken breast (330 cal) + large steamed vegetable plate — cauliflower, cabbage, carrot, shim, beans (100 cal) + ½ cup brown rice (108 cal) + ½ cup Arong doi (80 cal) + ½ banana (45 cal) · Meal-prep this on training days — cook a large batch of chicken and rice, portion into containers. Season with salt, ginger, green chili, lemon juice — zero oil needed" },
  ],
  snacks: [
    { name:"Large Arong Doi + Banana + Guava", kcal:247, emoji:"🍶" },
    { name:"3 Boiled Eggs + Cucumber + Tomato", kcal:225, emoji:"🥚" },
    { name:"Roasted Chana (Bengal Gram) 65g", kcal:221, emoji:"🫘" },
    { name:"2× Egg White Omelette (6 whites each)", kcal:204, emoji:"🍳" },
    { name:"Large Fruit Chaat (papaya+guava+banana+watermelon)", kcal:220, emoji:"🍉" },
    { name:"2× PRAN Flavored Yogurt Cups + Guava", kcal:240, emoji:"🥛", approx:true },
    { name:"Full Can Tuna (185g) + 4 Olympic Crackers", kcal:230, emoji:"🐟", approx:true },
  ]
};

const EXERCISES = [
  "Goblet Squat (A1)", "Calf Raises (A2)",
  "DB Pullover (B1)", "Floor Press (B2)", "Bent-Over Row (B3)",
  "Overhead Press (C1)", "Lateral Raises (C2)", "Glute Bridges (C3)",
  "Bicep Curls (C4)", "Skullcrushers (C5)", "Reverse Flyes (C6)"
];

const CHECKLIST_ITEMS = [
  { id:"workout", label:"Complete workout" },
  { id:"protein", label:"Hit protein goal" },
  { id:"water",   label:"Drink enough water" },
  { id:"cardio",  label:"Do cardio session" },
  { id:"sleep",   label:"Plan for 7–8h sleep" },
  { id:"vitamins",label:"Take vitamins / supplements" },
];


